version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
  heroku: circleci/heroku@1.2.6

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git

workflows:
  test_and_heroku_deploy:
    jobs:
      - cypress/install:
          build: 'npm run build' # run a custom app build step
          # start: npm start
      - cypress/run:
          requires:
            - cypress/install
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm start' # start server before running tests
      - deploy:
          requires:
            - cypress/run
          filters:
            branches:
              only: main

# version: 2.1

# orbs:
#   cypress: cypress-io/cypress@1.1.0

# workflows:
#   build:
#     jobs:
#       - cypress/run


# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # node: circleci/node@4.7

# cypress: cypress-io/cypress@1.29.0
# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:

#   # sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#   #   # Inside the workflow, you define the jobs you want to run.
#     jobs:
#     - cypress/install: 
#       build: 'npm run build'
#     - cypress/run: 
#       requires: 
#         - cypress/install
#       parallel: true
#       parallelism: 4
#       group: 'all tests'
#       start: 'npm start' 
#   #     - node/test:
  #         # This is the node version to use for the `cimg/node` tag
  #         # Relevant tags can be found on the CircleCI Developer Hub
  #         # https://circleci.com/developer/images/image/cimg/node
  #         version: '16.10'
  #         # If you are using yarn, change the line below from "npm" to "yarn"
  #         pkg-manager: npm
